# Generated by Django 3.2.18 on 2023-09-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
